### ISSUE TITLE
Update Go version for locality-checker

### ISSUE THREAD

**Issue by BobFerris** [cockroachdb/k8s#37]
The locality-checker container image is failing security audits due to vulnerabilities in earlier versions of Go.  Update locality-checker to use the latest Go version.

**Comment by davidwding** [comment]
This should be fixed. The Docker Hub locality-checker image [51fabcb38a3a4b9605a9d1fac11743d483667a9b](https://hub.docker.com/layers/locality-checker/cockroachdb/locality-checker/51fabcb38a3a4b9605a9d1fac11743d483667a9b/images/sha256-851eed624e90b2a94e27376efcbf040ffe05a9e5a6b0ed93b666c0e29f362407?context=explore) is on Go 1.17.
